services:
  novatel:
    image: ros2-novatel-driver
    build:
      context: .
      dockerfile: docker/Dockerfile.build
    entrypoint: "sleep infinity"
    network_mode: host
    privileged: true
    devices:
      - /dev/ttyUSB0
      - /dev/ttyUSB1
      - /dev/ttyUSB2
    volumes:
      - /dev:/dev
      - /lib/firmware:/lib/firmware
      - /tmp/.X11-unix:/tmp/.X11-unix
    # command: >
    #   oem7_file_name:=/dev/ttyUSB0 
    #   oem7_tty_baud:=115200
