ARG ROS_DISTRO=jazzy
ARG ROS_ARCH=amd64


FROM ${ROS_ARCH}/ros:${ROS_DISTRO}


ARG ROS_DISTRO
ARG ROS=ros-${ROS_DISTRO}

SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get install -y sudo vim nano curl socat python3-pip


RUN apt-get update && apt-get install -y \
    ros-${ROS_DISTRO}-rmw-cyclonedds-cpp \
    ros-${ROS_DISTRO}-cyclonedds
ENV RMW_IMPLEMENTATION=rmw_cyclonedds_cpp

WORKDIR /novatel_ros2/ros2_ws
COPY src ros2_ws/src
RUN rosdep update --include-eol-distros
RUN rosdep install --from-paths ros2_ws/src/ -y --ignore-src

RUN source /opt/ros/${ROS_DISTRO}/setup.bash && colcon build --base-paths ros2_ws/src/

RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> ~/.bashrc
RUN echo "source /novatel_ros2/ros2_ws/install/setup.bash" >> ~/.bashrc

ENTRYPOINT ["bash", "-c", "set -e \
    && source /opt/ros/${ROS_DISTRO}/setup.bash && \
    source /novatel_ros2/ros2_ws/install/setup.bash && \
    ros2 launch /novatel_ros2/ros2_ws/ros2_ws/src/novatel_oem7_driver/launch/oem7_file.launch.py \
    oem7_file_name:=/dev/ttyUSB0"]
