ARG ROS_DISTRO=kilted
ARG ROS_ARCH=amd64

FROM ${ROS_ARCH}/ros:${ROS_DISTRO}

RUN apt-get update && apt-get install -y sudo vim nano curl socat python3-pip python3-bloom python3-nose python3-rosdoc2

COPY ./entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

WORKDIR /ros2_ws
COPY . /ros2_ws/src/

RUN rosdep update --include-eol-distros && rosdep install --from-paths src -r -y

RUN /bin/bash -c "source /opt/ros/kilted/setup.bash && colcon build --symlink-install --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON"

RUN echo "source /ros2_ws/install/setup.bash" >> /root/.bashrc

ENTRYPOINT ["/entrypoint.sh"]
